# Generated by Django 6.1 on 2026-08-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="rbac.UserRole",
                through_fields=("user", "role"),
                to="rbac.role",
            ),
        ),
    ]
