# Generated by Django 6.1 on 2026-09-03 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='rbac.UserRole', through_fields=('user', 'role'), to='rbac.role'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='organization.organization'),
        ),
    ]
