# Generated by Django 6.1 on 2026-09-24 15:57

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def lowercase_emails(apps, schema_editor):
    """Refuses to run (rather than guessing which account to keep) if any
    email/username already collides case-insensitively - the constraints
    below can't be created over existing duplicates, and silently merging or
    renaming someone's login is not a migration's call to make. Otherwise
    lowercases every stored email, matching User.save()'s normalization."""
    User = apps.get_model("accounts", "User")
    for field in ("email", "username"):
        duplicates = (
            User.objects.exclude(**{f"{field}__isnull": True})
            .annotate(normalized=Lower(field))
            .values("normalized")
            .annotate(count=Count("id"))
            .filter(count__gt=1)
            .values_list("normalized", flat=True)
        )
        if duplicates:
            raise RuntimeError(
                f"Can't add the case-insensitive unique constraint on User.{field}: these values are "
                f"shared by more than one account (ignoring case): {', '.join(sorted(duplicates))}. "
                "Rename or remove the duplicate accounts, then re-run migrate."
            )
    for user in User.objects.all().only("id", "email"):
        lowered = user.email.strip().lower()
        if lowered != user.email:
            User.objects.filter(pk=user.pk).update(email=lowered)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_picture'),
        ('files', '0004_backfill_confirmed_at'),
        ('organization', '0003_remove_organizationsettings_primary_domain'),
        ('rbac', '0002_seed_bootstrap_rbac'),
    ]

    operations = [
        migrations.RunPython(lowercase_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='accounts_user_username_ci_unique'),
        ),
    ]
