# Generated by Django 6.1 on 2026-09-01 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.-]{3,30}$', 'Usernames can only contain letters, numbers, dots, underscores, and hyphens (3-30 characters).')]),
        ),
    ]
