# Generated by Django 6.1 on 2026-09-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_username'),
        ('organization', '0005_organization_remove_organizationsettings_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organization.organization'),
            preserve_default=False,
        ),
    ]
