# Generated by Django 6.1 on 2026-08-29 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="AeroKMS", max_length=200)),
                ("primary_domain", models.CharField(blank=True, max_length=255)),
                ("default_language", models.CharField(default="en-US", max_length=20)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("primary_color", models.CharField(default="#1D4ED8", max_length=7)),
                ("secondary_color", models.CharField(default="#505F76", max_length=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.storedfile",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.storedfile",
                    ),
                ),
            ],
        ),
    ]
