# Generated by Django 6.1 on 2026-09-03 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='organization.organization')),
                ('name', models.CharField(default='Athar', max_length=200)),
                ('primary_domain', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#1D4ED8', max_length=7)),
                ('secondary_color', models.CharField(default='#505F76', max_length=7)),
                ('primary_color_dark', models.CharField(default='#B7C4FF', max_length=7)),
                ('secondary_color_dark', models.CharField(default='#B8C7E2', max_length=7)),
                ('product_tour_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile')),
            ],
        ),
    ]
