# Generated by Django 6.1 on 2026-08-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='timezone',
        ),
    ]
