# Generated by Django 6.1 on 2026-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organizationsettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='primary_color_dark',
            field=models.CharField(default='#B7C4FF', max_length=7),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='secondary_color_dark',
            field=models.CharField(default='#B8C7E2', max_length=7),
        ),
    ]
