# Generated by Django 6.1 on 2026-09-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_seed_bootstrap_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='primary_domain',
        ),
    ]
