# Generated by Django 6.1 on 2026-08-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationsettings_primary_color_dark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='default_language',
        ),
    ]
