# Generated by Django 6.1 on 2026-09-02 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


# Bootstrap organization - this fixed all-zero UUID is deliberately what
# every other app's migrations (accounts/audit/files/knowledge/rbac,
# generated in the same multi-tenancy retrofit) use as their own new
# `organization` FK's one-off migration default, since some tables (e.g.
# knowledge_category, seeded by an earlier data migration) already have rows
# by the time those AddField operations run. Creating a real Organization
# row at that exact id here, before any of those run, is what makes those
# defaults resolve to a real FK target instead of failing with an
# IntegrityError. Real installs get their first proper Organization via
# organization.services.create_organization immediately after this migrates;
# this row is a migration-time bootstrap fixture, not meant to be "the org"
# forever - rename/repurpose it (or create additional real ones) freely.
BOOTSTRAP_ORGANIZATION_ID = "00000000-0000-0000-0000-000000000000"


def create_bootstrap_organization(apps, schema_editor):
    # Just the Organization row here - RBAC seeding for it happens in
    # organization.0006, a separate migration that can depend on both this
    # one and the rbac migration that adds Role.organization, without this
    # migration needing to depend on that later rbac migration itself
    # (which would be circular, since that rbac migration already depends on
    # this one for the Organization model its own new FK points at).
    Organization = apps.get_model("organization", "Organization")
    Organization.objects.get_or_create(
        id=BOOTSTRAP_ORGANIZATION_ID,
        defaults={"name": "Default Organization", "slug": "default"},
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organizationsettings_default_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_bootstrap_organization, noop_reverse),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='id',
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='organization',
            field=models.OneToOneField(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='organization.organization'),
            preserve_default=False,
        ),
    ]
