from django.urls import path

from .views import (
    AccessGrantDetailView,
    AccessGrantListCreateView,
    AnswerDetailView,
    AnswerListCreateView,
    ArticleArchiveView,
    ArticleAttachmentDetailView,
    ArticleAttachmentListView,
    ArticleDetailView,
    ArticleListCreateView,
    ArticlePublishView,
    ArticleRejectView,
    ArticleRelationsView,
    ArticleRevisionListView,
    ArticleSubmitView,
    ArticleUnarchiveView,
    BookmarkDetailView,
    BookmarkListCreateView,
    CategoryDetailView,
    CategoryListView,
    ComponentAttachmentDetailView,
    ComponentCategoryDetailView,
    ComponentCategoryListView,
    ComponentAttachmentListView,
    ComponentDetailView,
    ComponentExportView,
    ComponentImportTemplateView,
    ComponentImportView,
    ComponentInventorySummaryView,
    ComponentListCreateView,
    ComponentRelationsView,
    DocumentDetailView,
    DocumentListCreateView,
    DocumentRelationsView,
    FailureAttachmentDetailView,
    FailureAttachmentListView,
    FailureDetailView,
    FailureListCreateView,
    FailureRelationsView,
    LeaderboardView,
    OrgMembersListView,
    ProjectAttachmentDetailView,
    ProjectAttachmentListView,
    ProjectDetailView,
    ProjectListCreateView,
    ProjectRelationsView,
    QuestionAcceptAnswerView,
    QuestionAttachmentDetailView,
    QuestionAttachmentListView,
    QuestionCloseView,
    QuestionDetailView,
    QuestionListCreateView,
    QuestionPromoteView,
    QuestionRelationsView,
    QuestionReopenView,
    RelationCreateView,
    RelationDetailView,
    SearchView,
    SopAttachmentDetailView,
    SopAttachmentListView,
    SopDetailView,
    SopListCreateView,
    SopRelationsView,
    StorageLocationDetailView,
    StorageLocationListView,
    TagDetailView,
    TagListView,
    TestAttachmentDetailView,
    TestAttachmentListView,
    TestDetailView,
    TestListCreateView,
    TestRelationsView,
    UserContributionsView,
    UserProfileView,
)

urlpatterns = [
    path("search/", SearchView.as_view(), name="knowledge-search"),
    path("leaderboard/", LeaderboardView.as_view(), name="knowledge-leaderboard"),
    path("users/<uuid:pk>/", UserProfileView.as_view(), name="knowledge-user-profile"),
    path("users/<uuid:pk>/contributions/", UserContributionsView.as_view(), name="knowledge-user-contributions"),
    path("categories/", CategoryListView.as_view(), name="knowledge-category-list"),
    path("categories/<uuid:pk>/", CategoryDetailView.as_view(), name="knowledge-category-detail"),
    path("tags/", TagListView.as_view(), name="knowledge-tag-list"),
    path("tags/<uuid:pk>/", TagDetailView.as_view(), name="knowledge-tag-detail"),
    path("articles/", ArticleListCreateView.as_view(), name="knowledge-article-list-create"),
    path("articles/<uuid:pk>/", ArticleDetailView.as_view(), name="knowledge-article-detail"),
    path("articles/<uuid:pk>/submit/", ArticleSubmitView.as_view(), name="knowledge-article-submit"),
    path("articles/<uuid:pk>/publish/", ArticlePublishView.as_view(), name="knowledge-article-publish"),
    path("articles/<uuid:pk>/reject/", ArticleRejectView.as_view(), name="knowledge-article-reject"),
    path("articles/<uuid:pk>/archive/", ArticleArchiveView.as_view(), name="knowledge-article-archive"),
    path("articles/<uuid:pk>/unarchive/", ArticleUnarchiveView.as_view(), name="knowledge-article-unarchive"),
    path("articles/<uuid:pk>/revisions/", ArticleRevisionListView.as_view(), name="knowledge-article-revisions"),
    path("articles/<uuid:pk>/relations/", ArticleRelationsView.as_view(), name="knowledge-article-relations"),
    path(
        "articles/<uuid:pk>/attachments/",
        ArticleAttachmentListView.as_view(),
        name="knowledge-article-attachment-list",
    ),
    path(
        "articles/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        ArticleAttachmentDetailView.as_view(),
        name="knowledge-article-attachment-detail",
    ),
    path("questions/", QuestionListCreateView.as_view(), name="knowledge-question-list-create"),
    path("questions/<uuid:pk>/", QuestionDetailView.as_view(), name="knowledge-question-detail"),
    path("questions/<uuid:pk>/answers/", AnswerListCreateView.as_view(), name="knowledge-answer-list-create"),
    path("questions/<uuid:pk>/accept/", QuestionAcceptAnswerView.as_view(), name="knowledge-question-accept"),
    path("questions/<uuid:pk>/close/", QuestionCloseView.as_view(), name="knowledge-question-close"),
    path("questions/<uuid:pk>/reopen/", QuestionReopenView.as_view(), name="knowledge-question-reopen"),
    path("questions/<uuid:pk>/promote/", QuestionPromoteView.as_view(), name="knowledge-question-promote"),
    path("questions/<uuid:pk>/relations/", QuestionRelationsView.as_view(), name="knowledge-question-relations"),
    path(
        "questions/<uuid:pk>/attachments/",
        QuestionAttachmentListView.as_view(),
        name="knowledge-question-attachment-list",
    ),
    path(
        "questions/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        QuestionAttachmentDetailView.as_view(),
        name="knowledge-question-attachment-detail",
    ),
    path("answers/<uuid:pk>/", AnswerDetailView.as_view(), name="knowledge-answer-detail"),
    path("relations/", RelationCreateView.as_view(), name="knowledge-relation-create"),
    path("relations/<uuid:pk>/", RelationDetailView.as_view(), name="knowledge-relation-detail"),
    path("access-grants/", AccessGrantListCreateView.as_view(), name="knowledge-access-grant-create"),
    path("access-grants/<uuid:pk>/", AccessGrantDetailView.as_view(), name="knowledge-access-grant-detail"),
    path("org-members/", OrgMembersListView.as_view(), name="knowledge-org-members"),
    path("bookmarks/", BookmarkListCreateView.as_view(), name="knowledge-bookmark-list-create"),
    path("bookmarks/<uuid:pk>/", BookmarkDetailView.as_view(), name="knowledge-bookmark-detail"),
    # --- Engineering domain -------------------------------------------------
    path("projects/", ProjectListCreateView.as_view(), name="knowledge-project-list-create"),
    path("projects/<uuid:pk>/", ProjectDetailView.as_view(), name="knowledge-project-detail"),
    path("projects/<uuid:pk>/relations/", ProjectRelationsView.as_view(), name="knowledge-project-relations"),
    path(
        "projects/<uuid:pk>/attachments/",
        ProjectAttachmentListView.as_view(),
        name="knowledge-project-attachment-list",
    ),
    path(
        "projects/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        ProjectAttachmentDetailView.as_view(),
        name="knowledge-project-attachment-detail",
    ),
    path("components/", ComponentListCreateView.as_view(), name="knowledge-component-list-create"),
    path("components/export/", ComponentExportView.as_view(), name="knowledge-component-export"),
    path(
        "components/inventory-summary/",
        ComponentInventorySummaryView.as_view(),
        name="knowledge-component-inventory-summary",
    ),
    path("components/categories/", ComponentCategoryListView.as_view(), name="knowledge-component-category-list"),
    path(
        "components/categories/<uuid:pk>/",
        ComponentCategoryDetailView.as_view(),
        name="knowledge-component-category-detail",
    ),
    path("components/locations/", StorageLocationListView.as_view(), name="knowledge-storage-location-list"),
    path(
        "components/locations/<uuid:pk>/",
        StorageLocationDetailView.as_view(),
        name="knowledge-storage-location-detail",
    ),
    path("components/import/", ComponentImportView.as_view(), name="knowledge-component-import"),
    path(
        "components/import/template/",
        ComponentImportTemplateView.as_view(),
        name="knowledge-component-import-template",
    ),
    path("components/<uuid:pk>/", ComponentDetailView.as_view(), name="knowledge-component-detail"),
    path("components/<uuid:pk>/relations/", ComponentRelationsView.as_view(), name="knowledge-component-relations"),
    path(
        "components/<uuid:pk>/attachments/",
        ComponentAttachmentListView.as_view(),
        name="knowledge-component-attachment-list",
    ),
    path(
        "components/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        ComponentAttachmentDetailView.as_view(),
        name="knowledge-component-attachment-detail",
    ),
    path("failures/", FailureListCreateView.as_view(), name="knowledge-failure-list-create"),
    path("failures/<uuid:pk>/", FailureDetailView.as_view(), name="knowledge-failure-detail"),
    path("failures/<uuid:pk>/relations/", FailureRelationsView.as_view(), name="knowledge-failure-relations"),
    path(
        "failures/<uuid:pk>/attachments/",
        FailureAttachmentListView.as_view(),
        name="knowledge-failure-attachment-list",
    ),
    path(
        "failures/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        FailureAttachmentDetailView.as_view(),
        name="knowledge-failure-attachment-detail",
    ),
    path("sops/", SopListCreateView.as_view(), name="knowledge-sop-list-create"),
    path("sops/<uuid:pk>/", SopDetailView.as_view(), name="knowledge-sop-detail"),
    path("sops/<uuid:pk>/relations/", SopRelationsView.as_view(), name="knowledge-sop-relations"),
    path("sops/<uuid:pk>/attachments/", SopAttachmentListView.as_view(), name="knowledge-sop-attachment-list"),
    path(
        "sops/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        SopAttachmentDetailView.as_view(),
        name="knowledge-sop-attachment-detail",
    ),
    path("tests/", TestListCreateView.as_view(), name="knowledge-test-list-create"),
    path("tests/<uuid:pk>/", TestDetailView.as_view(), name="knowledge-test-detail"),
    path("tests/<uuid:pk>/relations/", TestRelationsView.as_view(), name="knowledge-test-relations"),
    path("tests/<uuid:pk>/attachments/", TestAttachmentListView.as_view(), name="knowledge-test-attachment-list"),
    path(
        "tests/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        TestAttachmentDetailView.as_view(),
        name="knowledge-test-attachment-detail",
    ),
    path("documents/", DocumentListCreateView.as_view(), name="knowledge-document-list-create"),
    path("documents/<uuid:pk>/", DocumentDetailView.as_view(), name="knowledge-document-detail"),
    path("documents/<uuid:pk>/relations/", DocumentRelationsView.as_view(), name="knowledge-document-relations"),
]
