from django.urls import path

from .views import (
    AnswerDetailView,
    AnswerListCreateView,
    ArticleArchiveView,
    ArticleDetailView,
    ArticleListCreateView,
    ArticlePublishView,
    ArticleRejectView,
    ArticleRevisionListView,
    ArticleSubmitView,
    CategoryDetailView,
    CategoryListView,
    QuestionAcceptAnswerView,
    QuestionCloseView,
    QuestionDetailView,
    QuestionListCreateView,
    QuestionPromoteView,
    QuestionReopenView,
    SearchView,
    TagDetailView,
    TagListView,
)

urlpatterns = [
    path("search/", SearchView.as_view(), name="knowledge-search"),
    path("categories/", CategoryListView.as_view(), name="knowledge-category-list"),
    path("categories/<uuid:pk>/", CategoryDetailView.as_view(), name="knowledge-category-detail"),
    path("tags/", TagListView.as_view(), name="knowledge-tag-list"),
    path("tags/<uuid:pk>/", TagDetailView.as_view(), name="knowledge-tag-detail"),
    path("articles/", ArticleListCreateView.as_view(), name="knowledge-article-list-create"),
    path("articles/<uuid:pk>/", ArticleDetailView.as_view(), name="knowledge-article-detail"),
    path("articles/<uuid:pk>/submit/", ArticleSubmitView.as_view(), name="knowledge-article-submit"),
    path("articles/<uuid:pk>/publish/", ArticlePublishView.as_view(), name="knowledge-article-publish"),
    path("articles/<uuid:pk>/reject/", ArticleRejectView.as_view(), name="knowledge-article-reject"),
    path("articles/<uuid:pk>/archive/", ArticleArchiveView.as_view(), name="knowledge-article-archive"),
    path("articles/<uuid:pk>/revisions/", ArticleRevisionListView.as_view(), name="knowledge-article-revisions"),
    path("questions/", QuestionListCreateView.as_view(), name="knowledge-question-list-create"),
    path("questions/<uuid:pk>/", QuestionDetailView.as_view(), name="knowledge-question-detail"),
    path("questions/<uuid:pk>/answers/", AnswerListCreateView.as_view(), name="knowledge-answer-list-create"),
    path("questions/<uuid:pk>/accept/", QuestionAcceptAnswerView.as_view(), name="knowledge-question-accept"),
    path("questions/<uuid:pk>/close/", QuestionCloseView.as_view(), name="knowledge-question-close"),
    path("questions/<uuid:pk>/reopen/", QuestionReopenView.as_view(), name="knowledge-question-reopen"),
    path("questions/<uuid:pk>/promote/", QuestionPromoteView.as_view(), name="knowledge-question-promote"),
    path("answers/<uuid:pk>/", AnswerDetailView.as_view(), name="knowledge-answer-detail"),
]
