from django.urls import path

from .views import (
    AnswerDetailView,
    AnswerListCreateView,
    ArticleArchiveView,
    ArticleAttachmentDetailView,
    ArticleAttachmentListView,
    ArticleDetailView,
    ArticleListCreateView,
    ArticlePublishView,
    ArticleRejectView,
    ArticleRelationsView,
    ArticleRevisionListView,
    ArticleSubmitView,
    CategoryDetailView,
    CategoryListView,
    QuestionAcceptAnswerView,
    QuestionAttachmentDetailView,
    QuestionAttachmentListView,
    QuestionCloseView,
    QuestionDetailView,
    QuestionListCreateView,
    QuestionPromoteView,
    QuestionRelationsView,
    QuestionReopenView,
    RelationCreateView,
    RelationDetailView,
    SearchView,
    TagDetailView,
    TagListView,
)

urlpatterns = [
    path("search/", SearchView.as_view(), name="knowledge-search"),
    path("categories/", CategoryListView.as_view(), name="knowledge-category-list"),
    path("categories/<uuid:pk>/", CategoryDetailView.as_view(), name="knowledge-category-detail"),
    path("tags/", TagListView.as_view(), name="knowledge-tag-list"),
    path("tags/<uuid:pk>/", TagDetailView.as_view(), name="knowledge-tag-detail"),
    path("articles/", ArticleListCreateView.as_view(), name="knowledge-article-list-create"),
    path("articles/<uuid:pk>/", ArticleDetailView.as_view(), name="knowledge-article-detail"),
    path("articles/<uuid:pk>/submit/", ArticleSubmitView.as_view(), name="knowledge-article-submit"),
    path("articles/<uuid:pk>/publish/", ArticlePublishView.as_view(), name="knowledge-article-publish"),
    path("articles/<uuid:pk>/reject/", ArticleRejectView.as_view(), name="knowledge-article-reject"),
    path("articles/<uuid:pk>/archive/", ArticleArchiveView.as_view(), name="knowledge-article-archive"),
    path("articles/<uuid:pk>/revisions/", ArticleRevisionListView.as_view(), name="knowledge-article-revisions"),
    path("articles/<uuid:pk>/relations/", ArticleRelationsView.as_view(), name="knowledge-article-relations"),
    path(
        "articles/<uuid:pk>/attachments/",
        ArticleAttachmentListView.as_view(),
        name="knowledge-article-attachment-list",
    ),
    path(
        "articles/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        ArticleAttachmentDetailView.as_view(),
        name="knowledge-article-attachment-detail",
    ),
    path("questions/", QuestionListCreateView.as_view(), name="knowledge-question-list-create"),
    path("questions/<uuid:pk>/", QuestionDetailView.as_view(), name="knowledge-question-detail"),
    path("questions/<uuid:pk>/answers/", AnswerListCreateView.as_view(), name="knowledge-answer-list-create"),
    path("questions/<uuid:pk>/accept/", QuestionAcceptAnswerView.as_view(), name="knowledge-question-accept"),
    path("questions/<uuid:pk>/close/", QuestionCloseView.as_view(), name="knowledge-question-close"),
    path("questions/<uuid:pk>/reopen/", QuestionReopenView.as_view(), name="knowledge-question-reopen"),
    path("questions/<uuid:pk>/promote/", QuestionPromoteView.as_view(), name="knowledge-question-promote"),
    path("questions/<uuid:pk>/relations/", QuestionRelationsView.as_view(), name="knowledge-question-relations"),
    path(
        "questions/<uuid:pk>/attachments/",
        QuestionAttachmentListView.as_view(),
        name="knowledge-question-attachment-list",
    ),
    path(
        "questions/<uuid:pk>/attachments/<uuid:attachment_pk>/",
        QuestionAttachmentDetailView.as_view(),
        name="knowledge-question-attachment-detail",
    ),
    path("answers/<uuid:pk>/", AnswerDetailView.as_view(), name="knowledge-answer-detail"),
    path("relations/", RelationCreateView.as_view(), name="knowledge-relation-create"),
    path("relations/<uuid:pk>/", RelationDetailView.as_view(), name="knowledge-relation-detail"),
]
