"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, True),
)
# Local dev convenience: `docker-compose` and CI inject real env vars directly,
# but running manage.py on a bare host still picks up backend/.env if present.
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-vjy1t2t(ho=1=q)l9%0vm$vwu7(ai-mjzje*%q%8vr@1-dkm7(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Trust nginx's X-Forwarded-Proto for request.is_secure() - this app always
# sits behind nginx (see nginx/templates/), which sets this header itself
# from its own $scheme (see nginx/templates/locations.inc.template); Django
# never sees a client-supplied value directly, so this is safe to trust
# unconditionally.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Needed for full-text search (SearchVector/SearchQuery/SearchRank) and
    # trigram similarity (pg_trgm, enabled via core's migration 0001) - see
    # knowledge/search.py.
    "django.contrib.postgres",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "core",
    "accounts",
    "rbac",
    "audit",
    "files",
    "organization",
    "knowledge",
    "training",
    "backups",
]

AUTH_USER_MODEL = "accounts.User"

# Lets login accept either email or the optional username - see
# accounts/backends.py. Replaces (not adds to) the default ModelBackend,
# since EmailOrUsernameBackend already covers everything it does plus the
# username fallback.
AUTHENTICATION_BACKENDS = ["accounts.backends.EmailOrUsernameBackend"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    # No SQLite fallback - DATABASE_URL (Postgres) is required in every
    # environment, dev included. Raises ImproperlyConfigured if unset.
    "default": env.db("DATABASE_URL"),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# In DEBUG, skip collectstatic entirely (see docker/entrypoint.sh) - WhiteNoise
# serves straight from each app's static/ dir via Django's staticfiles finders
# instead of the collected STATIC_ROOT, and {% static %} resolves URLs
# directly rather than through the collectstatic-generated hash manifest
# (which wouldn't exist yet without it).
if DEBUG:
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- S3-compatible object storage (opt-in) ------------------------------
# Local disk (STORAGES["default"] above) is the zero-config self-hosted
# default. Set AWS_STORAGE_BUCKET_NAME to switch StoredFile's storage
# backend to any S3-compatible provider (AWS S3, Cloudflare R2, Backblaze
# B2, self-hosted MinIO, ...) - every file consumer in this app goes
# through StoredFile.file's storage API (.open()/.delete(), never .path/
# .url - see files/models.py's docstring), so this is the only place that
# needs to change; no view code depends on which backend is active.
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="")
if AWS_STORAGE_BUCKET_NAME:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "access_key": env("AWS_ACCESS_KEY_ID", default=""),
            "secret_key": env("AWS_SECRET_ACCESS_KEY", default=""),
            "region_name": env("AWS_S3_REGION_NAME", default=None),
            # Only needed for non-AWS S3-compatible providers (R2, MinIO, B2) -
            # leave unset for real AWS S3, where boto3 resolves the regional
            # endpoint from region_name on its own.
            "endpoint_url": env("AWS_S3_ENDPOINT_URL", default=None),
            # The bucket stays private - every file is served through an
            # authenticated Django view (FileDownloadView et al.), never a
            # direct/public bucket URL, so there's nothing for a public ACL
            # or a browser-facing querystring-signed URL to do here.
            "default_acl": "private",
            "querystring_auth": False,
            # MinIO and some other self-hosted S3-compatible servers need
            # "path" (bucket name in the URL path); real AWS S3 and most
            # managed providers want the default "virtual" (bucket as a
            # subdomain of the endpoint).
            "addressing_style": env("AWS_S3_ADDRESSING_STYLE", default="virtual"),
        },
    }

# Branding logo/favicon uploads are the only thing that uses the generic file
# upload endpoint today, hence a small default matching the Stitch design's
# "Max size: 2MB" note - raise this (or make it per-endpoint) once general
# document/resource uploads are built.
MAX_UPLOAD_SIZE_MB = env.int("MAX_UPLOAD_SIZE_MB", default=2)


# CORS
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=["http://localhost:3000"])
# Required so the browser sends/receives the httpOnly refresh-token cookie on
# cross-origin requests made with fetch(..., { credentials: "include" }).
CORS_ALLOW_CREDENTIALS = True


# Django REST Framework / JWT auth
# https://www.django-rest-framework.org/  https://django-rest-framework-simplejwt.readthedocs.io/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # BrowsableAPIRenderer only in DEBUG (handy for poking an endpoint by
    # hand locally) - outside it, DRF would otherwise still serve its own
    # styled HTML error page to a real browser navigating straight to an
    # API URL (e.g. an auth-gated file link, see files/views.py) purely
    # because the browser's Accept header prefers text/html. JSON-only in
    # production means that always comes back as plain JSON instead,
    # regardless of Accept.
    "DEFAULT_RENDERER_CLASSES": (
        ["rest_framework.renderers.JSONRenderer", "rest_framework.renderers.BrowsableAPIRenderer"]
        if DEBUG
        else ["rest_framework.renderers.JSONRenderer"]
    ),
    # Anon/User apply everywhere by default; the "auth" scope is opted into
    # explicitly (see accounts/views.py's LoginView/RegisterView/RefreshView)
    # for a much stricter rate, since those are the endpoints brute-forcing
    # actually pays off on.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": env("THROTTLE_ANON_RATE", default="60/min"),
        "user": env("THROTTLE_USER_RATE", default="300/min"),
        "auth": env("THROTTLE_AUTH_RATE", default="10/min"),
    },
}

# Throttle counters are cache-backed and persist for the life of the test
# process (not per-test) - without this, the many rapid logins each test's
# _login_with_role()/_register_and_login() helper performs would trip the
# "auth" scope well before most test modules even got to run. Login/Register/
# Refresh set their own throttle_classes=[ScopedRateThrottle] (see
# accounts/views.py), which ignores DEFAULT_THROTTLE_CLASSES entirely - a rate
# of None is DRF's documented way to turn a scope off, so clearing the classes
# list alone isn't enough; the "auth" rate itself has to go too.
if "test" in sys.argv:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"]["auth"] = None

SPECTACULAR_SETTINGS = {
    "TITLE": "Athar API",
    "DESCRIPTION": "Athar backend API - see docs/VISION.md for the product spec.",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env.int("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", default=15)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env.int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", default=7)
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "SIGNING_KEY": env("JWT_SIGNING_KEY", default="") or SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# The refresh token is never sent in a JSON body - it only ever travels as this
# httpOnly cookie, scoped to the auth endpoints that need to read it.
JWT_REFRESH_COOKIE_NAME = env("JWT_REFRESH_COOKIE_NAME", default="refresh_token")
# Deliberately "/" (not scoped to /api/v1/auth/): the Next.js proxy (proxy.ts)
# needs to see this cookie's presence on every page route on the frontend
# origin to decide whether to redirect to /login - cookie Path scoping is
# independent of which server ends up receiving the request, so a narrower
# path would make the cookie invisible to page requests entirely.
JWT_REFRESH_COOKIE_PATH = "/"
JWT_REFRESH_COOKIE_SECURE = env.bool("JWT_REFRESH_COOKIE_SECURE", default=not DEBUG)
JWT_REFRESH_COOKIE_SAMESITE = env("JWT_REFRESH_COOKIE_SAMESITE", default="Lax")
JWT_REFRESH_COOKIE_DOMAIN = env("JWT_REFRESH_COOKIE_DOMAIN", default="") or None

ENABLE_REGISTRATION = env.bool("ENABLE_REGISTRATION", default=True)


# Celery (background jobs - backups.tasks.generate_org_backup on demand, plus
# files.tasks.delete_unconfirmed_files on the schedule below)
# https://docs.celeryq.dev/en/stable/userguide/configuration.html
# config.celery's `namespace="CELERY"` maps CELERY_BROKER_URL here to Celery's
# own `broker_url` setting, etc.

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Tests run the task function inline instead of round-tripping through a
# real broker/worker - same "test" in sys.argv gate the throttle-rate
# override above uses, for the same reason (no Redis/worker process in CI).
CELERY_TASK_ALWAYS_EAGER = "test" in sys.argv
CELERY_TASK_EAGER_PROPAGATES = True

# Run by the `celery-beat` service (docker-compose.yml) - a plain in-code
# schedule rather than the django-celery-beat package, since this is the only
# periodic job and doesn't need runtime/admin-editable scheduling. Hourly
# comfortably beats StoredFile's own 24h grace period (see
# files/services.py's UNCONFIRMED_FILE_GRACE_PERIOD) without being chatty.
CELERY_BEAT_SCHEDULE = {
    "delete-unconfirmed-files": {
        "task": "files.tasks.delete_unconfirmed_files",
        "schedule": 3600.0,
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
