# Generated by Django 6.1 on 2026-09-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='component',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile'),
        ),
        migrations.AddField(
            model_name='component',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
