# Generated by Django 6.1 on 2026-08-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_manual_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='promoted_to_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_questions', to='knowledge.article'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ANSWERED', 'Answered'), ('SOLVED', 'Solved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
