# Generated by Django 6.1 on 2026-09-25 20:57

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_component_link_component_photo_and_more'),
        ('organization', '0003_remove_organizationsettings_primary_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('WORN', 'Worn'), ('NEEDS_REPAIR', 'Needs Repair'), ('BROKEN', 'Broken')], max_length=20),
        ),
        migrations.AddField(
            model_name='component',
            name='inventory_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='component',
            name='inventory_type',
            field=models.CharField(blank=True, choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')], max_length=20),
        ),
        migrations.AddField(
            model_name='component',
            name='min_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('IN_STOCK', 'In Stock'), ('LOW_STOCK', 'Low Stock'), ('MISSING', 'Missing / Need to Order'), ('ON_ORDER', 'On Order'), ('RETIRED', 'Retired / Broken')], max_length=20),
        ),
        migrations.AddField(
            model_name='component',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='component',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.CharField(blank=True, choices=[('CERTIFIED', 'Certified'), ('TESTING', 'Testing'), ('DEPRECATED', 'Deprecated')], default='TESTING', max_length=20),
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name_plural': 'component categories',
                'ordering': ['name'],
                'unique_together': {('organization', 'name'), ('organization', 'slug')},
            },
        ),
        # Component.category moves from the shared knowledge Category to its
        # own ComponentCategory. Not a plain AlterField: the existing ids point
        # at Category rows, so each component's category is copied (by name)
        # into a new ComponentCategory (0004), then the old FK is dropped (0005).
        migrations.AddField(
            model_name='component',
            name='component_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.componentcategory'),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='knowledge.storagelocation'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('name'), name='unique_storage_location_name_ci'),
        ),
    ]
