# Generated by Django 6.1 on 2026-08-30 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('knowledge', '0003_question_promoted_to_article_question_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('ORGANIZATION', 'Organization'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('ORGANIZATION', 'Organization'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.UUIDField()),
                ('target_object_id', models.UUIDField()),
                ('relation_type', models.CharField(default='RELATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_content_type', 'source_object_id'], name='knowledge_k_source__3263e4_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='knowledge_k_target__0024f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id', 'relation_type'), name='unique_knowledge_relation')],
            },
        ),
    ]
