# Generated by Django 6.1 on 2026-09-01 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('knowledge', '0006_component_componentattachment_failure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('FLIGHT', 'Flight Test'), ('THRUST', 'Thrust Test'), ('STRUCTURAL', 'Structural Test'), ('ELECTRICAL', 'Electrical Test'), ('GROUND', 'Ground Test'), ('SOFTWARE', 'Software Test'), ('CALIBRATION', 'Calibration'), ('EXPERIMENT', 'Experiment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('objective', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('configuration', models.TextField(blank=True)),
                ('procedure', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('pass_fail', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PARTIAL', 'Partial'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='knowledge.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='tests', to='knowledge.tag')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files.storedfile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge.test')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
