# Generated by Django 6.1 on 2026-09-01 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('knowledge', '0007_test_testattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('doc_type', models.CharField(choices=[('COMPETITION_REPORT', 'Competition Report'), ('TECHNICAL_REPORT', 'Technical Report'), ('RESEARCH_PAPER', 'Research Paper'), ('DATASHEET', 'Datasheet'), ('MANUAL', 'Manual'), ('REGULATION', 'Regulation'), ('PRESENTATION', 'Presentation'), ('TRAINING_MATERIAL', 'Training Material'), ('REFERENCE', 'Reference'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('source', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=10)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('ORGANIZATION', 'Organization'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='knowledge.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='files.storedfile')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='knowledge.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
