# Generated by Django 6.1 on 2026-09-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_document'),
        ('organization', '0005_organization_remove_organizationsettings_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='external_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='failure',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgerelation',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sop',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='organization',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=220),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name'), ('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('organization', 'name')},
        ),
    ]
