# Generated by Django 6.1 on 2026-09-03 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('knowledge', '0010_convert_organization_visibility_to_public'),
        ('organization', '0006_seed_bootstrap_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='failure',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='sop',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='knowledge_b_content_18d2e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='RestrictedAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('granted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='knowledge_r_content_6a8026_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'granted_user'), name='unique_restricted_access_grant')],
            },
        ),
    ]
