import {
  AlertTriangle,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  BadgeCheck,
  Ban,
  Bell,
  Bold,
  Bookmark,
  BookOpen,
  Building2,
  CalendarClock,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDashed,
  CirclePause,
  CircleSlash,
  CircleX,
  Clock,
  Code2,
  Compass,
  Construction,
  Copy,
  Cpu,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FilePen,
  FileText,
  FileUp,
  FlaskConical,
  Folder,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  HardDrive,
  HelpCircle,
  Hourglass,
  Image,
  Info,
  Italic,
  LayoutDashboard,
  LayoutGrid,
  Library,
  Link2,
  List,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu as MenuIcon,
  MessageSquare,
  Monitor,
  MonitorPlay,
  Moon,
  MoreVertical,
  Mountain,
  OctagonAlert,
  Package,
  Pencil,
  Plane,
  PlayCircle,
  Plus,
  Presentation,
  Rocket,
  Scale,
  ScrollText,
  Search,
  SearchCheck,
  Send,
  Settings,
  Share2,
  Sheet,
  ShieldCheck,
  ShoppingCart,
  SignalHigh,
  SignalLow,
  SignalMedium,
  Sparkles,
  Sun,
  Table,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Undo2,
  Upload,
  User,
  Users,
  Video,
  Workflow,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Maps the icon names used across the app (kept as the same short identifiers
// the old Material Symbols font used, so call sites and data-driven icon
// props - e.g. SideNav's NAV_ITEMS, Menu's MenuEntry.icon - didn't need to
// change) to their lucide-react equivalents.
const ICONS: Record<string, LucideIcon> = {
  account: User,
  add: Plus,
  admin_panel_settings: ShieldCheck,
  alternate_email: AtSign,
  architecture: Building2,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  article: ScrollText,
  auto_awesome: Sparkles,
  block: Ban,
  bolt: Zap,
  bookmark: Bookmark,
  build: Hammer,
  calendar_month: CalendarDays,
  cancel: CircleX,
  check: Check,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  close: X,
  code: Code2,
  computer: Monitor,
  construction: Construction,
  content_copy: Copy,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  datasheet: Sheet,
  delete: Trash2,
  description: FileText,
  diagram: Workflow,
  do_not_disturb: CircleSlash,
  domain: Building2,
  download: Download,
  draft: File,
  edit: Pencil,
  edit_note: FilePen,
  emoji_events: Trophy,
  event_upcoming: CalendarClock,
  expand_more: ChevronDown,
  flight: Plane,
  folder: Folder,
  folder_open: FolderOpen,
  fork_right: GitBranch,
  format_bold: Bold,
  format_italic: Italic,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  forum: MessageSquare,
  gavel: Scale,
  grid_view: LayoutGrid,
  group: Users,
  handyman: Wrench,
  hard_drive: HardDrive,
  help: HelpCircle,
  hourglass: Hourglass,
  hub: Share2,
  image: Image,
  info: Info,
  inventory: Package,
  label: Tag,
  landscape: Mountain,
  language: Globe,
  light_mode: Sun,
  link: Link2,
  local_library: Library,
  local_shipping: Truck,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  manage_search: SearchCheck,
  menu: MenuIcon,
  menu_book: BookOpen,
  more_horiz: Ellipsis,
  more_vert: MoreVertical,
  notifications: Bell,
  open_in_new: ExternalLink,
  pause_circle: CirclePause,
  pending: LoaderCircle,
  place: MapPin,
  play_circle: PlayCircle,
  public: Globe,
  rate_review: Eye,
  report: OctagonAlert,
  report_problem: AlertTriangle,
  rocket_launch: Rocket,
  schedule: Clock,
  school: GraduationCap,
  science: FlaskConical,
  search: Search,
  send: Send,
  settings: Settings,
  settings_input_component: Cpu,
  share: Share2,
  shopping_cart: ShoppingCart,
  signal_high: SignalHigh,
  signal_low: SignalLow,
  signal_medium: SignalMedium,
  slideshow: Presentation,
  smart_display: MonitorPlay,
  speed: Gauge,
  table_chart: Table,
  timelapse: CircleDashed,
  travel_explore: Compass,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  trophy: Award,
  unarchive: ArchiveRestore,
  undo: Undo2,
  upload: Upload,
  upload_file: FileUp,
  verified: BadgeCheck,
  videocam: Video,
  visibility: Eye,
  visibility_off: EyeOff,
};

interface IconProps {
  name: string;
  className?: string;
  /** Solid fill instead of outline - only reaches for this on simple glyphs
   * (e.g. BrandMark's "hub" logomark) where filling the shape solid still
   * reads cleanly. Detail-heavy icons (a book's page-fold, a gear's teeth)
   * lose that detail when filled, so nav "selected" state doesn't use this -
   * it gets its emphasis from the pill background + bold label instead (see
   * SideNav.tsx). */
  filled?: boolean;
  size?: number;
}

export function Icon({ name, className, filled, size }: IconProps) {
  const LucideIconComponent = ICONS[name];
  if (!LucideIconComponent) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`Icon: no lucide-react mapping for "${name}"`);
    }
    return null;
  }

  return (
    <LucideIconComponent
      className={className}
      size={size ?? 24}
      strokeWidth={2}
      fill={filled ? "currentColor" : "none"}
      aria-hidden="true"
    />
  );
}
