# Generated by Django 6.1 on 2026-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20),
        ),
    ]
