from django.urls import path

from .views import (
    CourseAccessGrantDetailView,
    CourseAccessGrantListCreateView,
    CourseArchiveView,
    CourseCategoryDetailView,
    CourseCategoryListView,
    CourseDetailView,
    CourseEnrollView,
    CourseListCreateView,
    CourseModuleDetailView,
    CourseModuleListCreateView,
    CourseModuleReorderView,
    CoursePublishView,
    CourseProgressView,
    CourseRejectView,
    CourseStatsView,
    CourseSubmitView,
    CourseUnarchiveView,
    KnowledgeReferenceDetailView,
    LessonCompleteView,
    LessonDetailView,
    LessonKnowledgeReferenceListCreateView,
    LessonObjectiveReorderView,
    LessonObjectiveListCreateView,
    LessonResourceListCreateView,
    LessonResourceReorderView,
    ModuleLessonListCreateView,
    ModuleLessonReorderView,
    MyCoursesView,
    ObjectiveDetailView,
    ResourceDetailView,
    TrainingSearchView,
    TrainingStatsView,
)

urlpatterns = [
    path("search/", TrainingSearchView.as_view(), name="training-search"),
    path("stats/", TrainingStatsView.as_view(), name="training-stats"),
    path("my-courses/", MyCoursesView.as_view(), name="training-my-courses"),
    path("categories/", CourseCategoryListView.as_view(), name="training-category-list"),
    path("categories/<uuid:pk>/", CourseCategoryDetailView.as_view(), name="training-category-detail"),
    path("courses/", CourseListCreateView.as_view(), name="training-course-list-create"),
    path("courses/<uuid:pk>/", CourseDetailView.as_view(), name="training-course-detail"),
    path("courses/<uuid:pk>/submit/", CourseSubmitView.as_view(), name="training-course-submit"),
    path("courses/<uuid:pk>/publish/", CoursePublishView.as_view(), name="training-course-publish"),
    path("courses/<uuid:pk>/reject/", CourseRejectView.as_view(), name="training-course-reject"),
    path("courses/<uuid:pk>/archive/", CourseArchiveView.as_view(), name="training-course-archive"),
    path("courses/<uuid:pk>/unarchive/", CourseUnarchiveView.as_view(), name="training-course-unarchive"),
    path(
        "courses/<uuid:pk>/access-grants/",
        CourseAccessGrantListCreateView.as_view(),
        name="training-course-access-grant-list-create",
    ),
    path(
        "courses/<uuid:pk>/access-grants/<uuid:grant_pk>/",
        CourseAccessGrantDetailView.as_view(),
        name="training-course-access-grant-detail",
    ),
    path("courses/<uuid:pk>/enroll/", CourseEnrollView.as_view(), name="training-course-enroll"),
    path("courses/<uuid:pk>/progress/", CourseProgressView.as_view(), name="training-course-progress"),
    path("courses/<uuid:pk>/stats/", CourseStatsView.as_view(), name="training-course-stats"),
    path("courses/<uuid:pk>/modules/", CourseModuleListCreateView.as_view(), name="training-module-list-create"),
    path("courses/<uuid:pk>/modules/reorder/", CourseModuleReorderView.as_view(), name="training-module-reorder"),
    path("modules/<uuid:pk>/", CourseModuleDetailView.as_view(), name="training-module-detail"),
    path("modules/<uuid:pk>/lessons/", ModuleLessonListCreateView.as_view(), name="training-lesson-list-create"),
    path("modules/<uuid:pk>/lessons/reorder/", ModuleLessonReorderView.as_view(), name="training-lesson-reorder"),
    path("lessons/<uuid:pk>/", LessonDetailView.as_view(), name="training-lesson-detail"),
    path("lessons/<uuid:pk>/complete/", LessonCompleteView.as_view(), name="training-lesson-complete"),
    path("lessons/<uuid:pk>/objectives/", LessonObjectiveListCreateView.as_view(), name="training-objective-list-create"),
    path(
        "lessons/<uuid:pk>/objectives/reorder/", LessonObjectiveReorderView.as_view(), name="training-objective-reorder"
    ),
    path("objectives/<uuid:pk>/", ObjectiveDetailView.as_view(), name="training-objective-detail"),
    path("lessons/<uuid:pk>/resources/", LessonResourceListCreateView.as_view(), name="training-resource-list-create"),
    path("lessons/<uuid:pk>/resources/reorder/", LessonResourceReorderView.as_view(), name="training-resource-reorder"),
    path("resources/<uuid:pk>/", ResourceDetailView.as_view(), name="training-resource-detail"),
    path(
        "lessons/<uuid:pk>/knowledge-references/",
        LessonKnowledgeReferenceListCreateView.as_view(),
        name="training-knowledge-reference-list-create",
    ),
    path(
        "knowledge-references/<uuid:pk>/",
        KnowledgeReferenceDetailView.as_view(),
        name="training-knowledge-reference-detail",
    ),
]
