# Generated by Django 6.1.2 on 2026-10-10 12:22

import backups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_uuid7_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorejob',
            name='uploaded_archive',
            field=models.FileField(blank=True, null=True, upload_to=backups.models.uploaded_restore_archive_path),
        ),
        migrations.AddField(
            model_name='restorejob',
            name='uploaded_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
