# Generated by Django 6.1 on 2026-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
